version: "3.8"

services:
  db:
    image: postgres:14.15
    container_name: vacation_db
    restart: always
    environment:
      POSTGRES_DB: vacation_portal
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5433:5432"
    volumes:
      - ./backend/database/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql:ro
      - ./backend/database/seed.sql:/docker-entrypoint-initdb.d/02-seed.sql:ro

  backend:
    build: ./backend
    container_name: vacation_backend
    restart: always
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: "postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}"
    env_file:
      - backend/.env
